### PR TITLE
devcontainer configuration for rudr dev environment.

### PR DESCRIPTION
**Pull request by dumbnose**
This is the initial .devcontainer config and Dockerfile to create the dev environment.

### CODE REVIEW

**Comment by wonderflow** [comment]
This is good, could you give some documentation for using this?

**Comment by dumbnose** [comment]
I can add docs.  But, this is just the standard VS Code Remote Container feature.  Where do you want the info to be added?

**Comment by technosophos** [comment]
I don't think any of us on this project have ever used that extension. So we don't know what to do with this PR. I guess it would be enough to add a document under `docs/developer` just pointing toward some external documentation on what this is and what it is supposed to do.

**Comment by dumbnose** [comment]
I'm adding a Quick Start section to the Contributing.md that explains how to use this to develop.

**Comment by dumbnose** [comment]
OK.  I added documentation.  Let me know what you think.

**Comment by dumbnose** [comment]
Is this still blocked?

**Comment by suhuruli** [comment]
@dumbnose , it would be good to add information on how this can be used for people trying to use Rudr instead of contribute to it as well. 

However, I think we can do that in separate follow up PRs. Thanks for this contribution. @wonderflow, can we merge this now?

**Comment by suhuruli** [comment]
I was writing some docs and @dumbnose, I think these docs make sense in the `docs/developer` folder. Can you move it in there?

**Comment by wonderflow** [comment]
After read the README, I find it seems this is only benifit for vscode users. I don't know whether we really want to add it to project.

Are we possible to setup dev environment like this by using Makefile ?

**Comment by suhuruli** [comment]
@wonderflow , what if there was a container that users can start by mounting the Scylla directory into and they have an environment which now contains kubectl, Docker, helm3, Rust etc. This allows customers on any platform to try out the examples, docs and also the VSCode experience.

**Comment by technosophos** [comment]
@suhuruli I believe that if we wanted to, we could add a third stage to the build in the Dockerfile which would do that. But it feels like sort of a niche thing that is not really part of the core experience for the project. Maybe we should put that in a separate repo where it could be built and then pushed to DockerHub. (That's closer to the way Dapr did their repo structure)

**Comment by suhuruli** [comment]
That's a great idea to have it as a step in the original Dockerfile.

**Comment by technosophos** [comment]
What is the final verdict on this? Do we need to just put something in here for now and move it later? Or have we found another place already?

**Comment by suhuruli** [comment]
> What is the final verdict on this? Do we need to just put something in here for now and move it later? Or have we found another place already?

I fixed up this PR and I think it's good to go now. I can be on point for the maintenance moving forward. 

1. Created a GitHub Action that runs on push which generates the dev container image. 
2. Split the contributing docs up into using the dev container image as an optional step for contributors
3. Separately, I believe we can also use the dev container image as part of Quickstart's and How-To's for people who want to consume Rudr and don't want to install all the dependencies etc.

**Pull request merged**
