### PR TITLE
Rudr samples - bikesharing from Microsoft 

### PR DESCRIPTION
**Pull request by sowsan**
Added two new Rudr examples by using the existing Microsoft Bikesharing360 samples.

Original BikeSharing 360 for single containers can be found [here](https://github.com/Microsoft/BikeSharing360_MultiContainer), and BikeSharing 360 for single containers can be found [here](https://github.com/microsoft/BikeSharing360_SingleContainer).

Multi-container app contains 3 APIs and a UI and single app is a one container app. 

BikeSharing360 is a fictitious example of a smart bike-sharing system with 10,000 bikes distributed in 650 stations located throughout New York City and Seattle. Their vision is to provide a modern and personalized experience to riders and to run their business with intelligence.

This was a team effort from Microsoft OCP app dev CSAs.

### CODE REVIEW

**Comment by hongchaodeng** [comment]
Could you move the changes to https://github.com/oam-dev/samples ?

**Comment by sowsan** [comment]
@hongchaodeng thanks for the directions. I just created a pull request for the same here, https://github.com/oam-dev/samples/pull/21

**Comment by sowsan** [comment]
@hongchaodeng , a suggestion, it would be great if we can keep a generalized readme file in the root of the https://github.com/oam-dev/samples and keep all of readme files specific to each sample in its own subfolders. The one that we have now in the root is talking about the service tracker sample.

**Comment by suhuruli** [comment]
Closing since the PR in the samples repo got merged :)

**Pull request closed without merging**
