### PR TITLE
make resource required and also fix examples to be consistent with spec

### LINKED ISSUE #364: The `resources` field should be required
According to the current version of the spec:

- the `container.resources` field is required
- the `container.resources.cpu` field is required
- the `container.resources.memory` field is required

I think this is bad, but... it is what the spec says, so we should fix that in Rudr.

### LINKED ISSUE #406: docs: Component Schematic concepts article misleading table
Under the **Container** section of the https://github.com/oam-dev/rudr/blob/master/docs/concepts/component-schematic.md#containers concept article, the resources row is not ticked as "required". This is partially misleading since some of the resources are required but not all (see [here](https://github.com/oam-dev/rudr/blob/master/docs/concepts/component-schematic.md#resources)). I think the resources row should be marked as required on the **Container** section

### PR DESCRIPTION
**Pull request by wonderflow**
though discussion is still undergoing（oam-dev/spec#218） , we could align resource requirement with OAM spec  v1.0.0-alpha.1, so we won't make confusion or misleading。 fixes #406 fixes #364

### CODE REVIEW

**Comment by wonderflow** [comment]
@technosophos  what if remove the default ? we make it **real required** in spec?

**Comment by suhuruli** [comment]
@technosophos , thoughts after @wonderflow's comment?

**Comment by resouer** [comment]
My thoughts on this: https://github.com/oam-dev/spec/pull/218#issuecomment-551317038, in short:

1. `resources` section could be optional but needed for claiming resource hints.
2. resource trait is the recommended way for ops to step in.
3. default value is a bad practice but it's a must for some platforms.

**Comment by wonderflow** [comment]
So what do you think about this PR now? @technosophos

**Pull request merged**
