### PR TITLE
Added images to docs/README.md

### PR DESCRIPTION
**Pull request by macolso**
- added a few visuals and refactored the **Concepts** section

### CODE REVIEW

**Comment by macolso** [comment]
@suhuruli

**Comment by suhuruli** [comment]
Hey, the images don't show up for me when I try to view the file. Are the paths correct?

**Comment by macolso** [comment]
paths are correct on my branch - it might be because I'm creating a folder to place the images in and it doesn't exist until the pr is merged?

**Comment by suhuruli** [comment]
> paths are correct on my branch - it might be because I'm creating a folder to place the images in and it doesn't exist until the pr is merged?

OK, I was just clicking the wrong thing. It shows up now. Nice!

**Comment by hongchaodeng** [comment]
LGTM

**Comment by hongchaodeng** [comment]
@wonderflow We can squash and merge the PR.

**Pull request merged**
