### PR TITLE
add service tracker sample and fix examples directory

### PR DESCRIPTION
**Pull request by suhuruli**
- Added the service tracker sample and source 
- Created an overview page in Examples so users know what each sample attempts to show off

### CODE REVIEW

**Comment by hongchaodeng** [comment]
Could you explain a bit more about _service tracker_ and what it does?

**Comment by suhuruli** [comment]
Multi-service app that shows a weather map, earthquake map and flight tracking map on a web UI. Each service (weather, earthquake and flights) are modeled as separate microservices with their own APIs exposed. There is a single microservice for the web UI and one for the data access. 

The plan is to use this sample to also show off how a GitHub Action pipeline can be used to build code from source, generate OAM manifests and deploy it to a K8s cluster. That PR will follow or be combined into this.

**Comment by hongchaodeng** [comment]
Sounds awesome!

One concern I have is that there are too many js files in this example. Maybe we can put the entire app in another repo, e.g. under _oam-dev_ org? And then we reference it, e.g. git clone?

**Comment by suhuruli** [comment]
@hongchaodeng , I agree. Let me close this PR, re-open a smaller one with just the Examples overview doc and I will create a separate repo for this sample.

**Pull request closed without merging**
