### PR TITLE
Added application scope comic

### PR DESCRIPTION
**Pull request by macolso**

### CODE REVIEW

**Comment by macolso** [comment]
looks like there's merge conflicts with the new doc structure, and I don't have permission to resolve them. Would either of you be able to resolve the conflicts, or should I delete the PR, rebased, and start a new one - @wonderflow, @hongchaodeng ?

**Comment by hongchaodeng** [comment]
Hi @macolso

To resolve the conflict, you just need to rebase on your local repo, fix any conflicts, and push the code again.

Maybe ask any of your programmer colleague to give you a hand. It is very trivial ;)

**Comment by macolso** [comment]
fixed the merge conflicts, @hongchaodeng !

**Comment by hongchaodeng** [comment]
Nice! Merging...

**Pull request merged**
